//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class deal
    {
        public int Id { get; set; }
        public Nullable<int> Demand_Id { get; set; }
        public Nullable<int> Supply_Id { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual supply supply { get; set; }
    }
}
