//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esoftEntities : DbContext
    {
        private static esoftEntities _context;
        public esoftEntities()
            : base("name=esoftEntities")
        {
        }
        public static esoftEntities GetContext()
        {
            if (_context == null)
                _context = new esoftEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agent> agents { get; set; }
        public virtual DbSet<apartment> apartments { get; set; }
        public virtual DbSet<apartments_demands> apartments_demands { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<deal> deals { get; set; }
        public virtual DbSet<Demand> Demands { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<house_demands> house_demands { get; set; }
        public virtual DbSet<house> houses { get; set; }
        public virtual DbSet<land_demands> land_demands { get; set; }
        public virtual DbSet<land> lands { get; set; }
        public virtual DbSet<supply> supplies { get; set; }
        public virtual DbSet<type> types { get; set; }
    }
}
